kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: paul-nfs-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: a-nfs
  storageClassName: powerstore-nfs
  volumeMode: Filesystem
