kind: PersistentVolume
apiVersion: v1
metadata:
  name: a-nfs
spec:
  capacity:
    storage: 20Gi
  nfs:
    server: 192.168.1.221
    path: /ocp
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: powerstore-nfs
  volumeMode: Filesystem

